### ISSUE TITLE
User-Agent Header Error

### ISSUE THREAD

**Issue by Ishrock** [Adyen/adyen-python-api-library#66]
**Python version**: 3.7.2
**Library version**: 2.0.0
**Description**

While following the API Integration guide, the suggested instantiation of the Adyen class is:

```python
adyen = Adyen.Adyen()
adyen.client.xapikey = 'YOUR X-API-KEY'
```

This will result in the following error.

```
Traceback (most recent call last):
  ...
  File ".../venv/lib/python3.7/site-packages/Adyen/httpclient.py", line 41, in __init__
    self.user_agent = app_name + " " + user_agent_suffix + lib_version
  TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

Because the default for `app_name` is `None` instead of an empty string, or another string type default value.

To get around this error, a user needs to read through the code here on github and discover that you can init the Adyen class by passing

```python
adyen = Adyen.Adyen(app_name="some arbitrary app name")
```

or

```python
adyen = Adyen.Adyen()
adyen.client.app_name = "some arbitrary app name"
```

My suggestion is to either change your documentation, fail with a more reasonable error message if an app_name is required, or update the code to have string type default value.

for example change line 74 of adyen/client.py from:
```python3
                 hmac=None, app_name=None,
```

to:
```python3
                 hmac=None, app_name="",
```

I have supplied code snippets bellow with links to code as well as line numbers for your reference.

https://github.com/Adyen/adyen-python-api-library/blob/develop/Adyen/__init__.py (line 29)
```python
class Adyen(AdyenBase):
    def __init__(self, **kwargs):
        self.client = AdyenClient(**kwargs)
        self.payment = AdyenPayment(client=self.client)
        self.payout = AdyenThirdPartyPayout(client=self.client)
        self.hpp = AdyenHPP(client=self.client)
        self.recurring = AdyenRecurring(client=self.client)
        self.checkout = AdyenCheckoutApi(client=self.client)
```

https://github.com/Adyen/adyen-python-api-library/blob/develop/Adyen/client.py (line 74, line 89, and any call to HTTPClient, such as line 217)
```python
class AdyenClient(object):
    def __init__(self, username=None, password=None, xapikey=None,
                 review_payout_username=None, review_payout_password=None,
                 store_payout_username=None, store_payout_password=None,
                 platform="test", merchant_account=None,
                 merchant_specific_url=None, skin_code=None,
                 hmac=None, app_name=None,
                 http_force=None, live_endpoint_prefix=None):
        self.username = username
        self.password = password
        self.xapikey = xapikey
        self.review_payout_username = review_payout_username
        self.review_payout_password = review_payout_password
        self.store_payout_username = store_payout_username
        self.store_payout_password = store_payout_password
        self.platform = platform
        self.merchant_specific_url = merchant_specific_url
        self.hmac = hmac
        self.merchant_account = merchant_account
        self.skin_code = skin_code
        self.psp_list = []
        self.app_name = app_name
        self.LIB_VERSION = settings.LIB_VERSION
        self.USER_AGENT_SUFFIX = settings.LIB_NAME + "/"
        self.http_init = False
        self.http_force = http_force
        self.live_endpoint_prefix = live_endpoint_prefix

        # any call to HTTPClient will fail because app_name is None
```

https://github.com/Adyen/adyen-python-api-library/blob/develop/Adyen/httpclient.py (line 41)
```python3
class HTTPClient(object):
    def __init__(self, app_name, user_agent_suffix,
                 lib_version, force_request=None):

        self.user_agent = app_name + " " + user_agent_suffix + lib_version
```

**Comment by AlexandrosMor** [comment]
Hello @Ishrock,
We are going to look the issue and we will let you know as soon as possible,

Kind regards,
Alexandros Moraitis
Adyen

**Comment by angrydill** [comment]
I can confirm I ran into the same issue running the "Get available payment methods" example.  We're running Python 3.4.1 on RHEL 7.6...

```Traceback (most recent call last):
  File "./mkprofile.py", line 16, in <module>
    'channel': 'Web',
  File "/tmp/rg-adyen-test/lib/python3.4/site-packages/Adyen/services.py", line 315, in payment_methods
    return self.client.call_checkout_api(request, action, **kwargs)
  File "/tmp/rg-adyen-test/lib/python3.4/site-packages/Adyen/client.py", line 401, in call_checkout_api
    self.http_force)
  File "/tmp/rg-adyen-test/lib/python3.4/site-packages/Adyen/httpclient.py", line 41, in __init__
    self.user_agent = app_name + " " + user_agent_suffix + lib_version
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```
Thanks,
Randy Gill

**Comment by Ishrock** [comment]
Opened a pull request to resolve the issue: https://github.com/Adyen/adyen-python-api-library/pull/67

**Comment by Ishrock** [comment]
closing, pr #67 solves issue

**Comment by jonaseriksson84** [comment]
I am running version 2.1.0 and I still get the User-Agent Header Error unless I instantiate with
adyen = Adyen.Adyen(name="whatever_name"). With it, everything works as expected.
